# Copyright 2026 Thomson Reuters
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: 'testdata/malformed\.json$'
      - id: check-toml
      - id: check-yaml
        exclude: 'testdata/invalid.*\.ya?ml$'
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: f298c082154b2cb239fac06a4f452368e66e66dd # v1.0.0-rc.4
    hooks:
      - id: go-mod-tidy
      - id: go-test-repo-mod
      - id: go-build-repo-mod
      - id: golangci-lint-mod
        args: [--fix]

  - repo: https://github.com/google/addlicense
    rev: 26c3b6c7f829e99495a2786d44b57cad4fae5b89 # v1.2.0
    hooks:
      - id: addlicense
        args:
          - -c
          - "Thomson Reuters"
          - -l
          - apache
          - -y
          - "2026"
          - -check
          - -ignore
          - "**/*.lock.hcl"
          - -ignore
          - ".ignored/**"

  # Markdown lint
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 996abf60411a8d954288ac9856aae7602b80cbda # v0.22.1
    hooks:
      - id: markdownlint-cli2-docker

  # GitHub Actions workflow lint
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint
